#extension GL_EXT_nonuniform_qualifier : enable

#define BINDLESS_DESCRIPTOR_SET 0
#define VERTEX_BINDLESS_PARAM_SET 1
#define FRAGMENT_BINDLESS_PARAM_SET 2

#define BINDLESS_UNIFORM_BUFFER_BINDING 0
#define BINDLESS_STORAGE_BUFFER_BINDING 1
#define BINDLESS_TEXTURE_SAMPLER_BINDING 2
